default_settings = {
	"KEEP_ALIVE_TIMEOUT": 2 ** 16,
	"WEBSOCKET_TIMEOUT": 2 ** 16,
	"WEBSOCKET_MAX_SIZE": 2 ** 20,
	"WEBSOCKET_MAX_QUEUE": 1024,
	"WEBSOCKET_READ_LIMIT": 2 ** 16,
	"WEBSOCKET_WRITE_LIMIT": 2 ** 16,
	"ACCESS_LOG": True,
}
